### ISSUE TITLE
rotor balancer

### ISSUE THREAD

**Issue by hstarmans** [ThunderFly-aerospace/TF-BladeBalancer#1]
I am also working on rotor balancer this might be of your interest see code here ; https://github.com/hstarmans/rotorbalancer

**Comment by kaklik** [comment]
Hi, @hstarmans I look at your balancer repository and I noticed that it is a quite different technique.  (I updated our readme to be more clearly described :) ) 

But it seems your method seems to be close to [another our issue](https://github.com/ThunderFly-aerospace/Hardware/issues/14) which we need to solve.   It would be perfect if we can join both devices. To make vibration testing and multi-copter rotor blade balancing instrument. Is something from us what could you help you?

**Comment by hstarmans** [comment]
Nice.. the description got a lot better.. I am building a dynamic balancer and not a static one. Here is a [dynamic prop balancer](https://www.itsqv.com/QVM/index.php?title=DIY_-_Dynamic_Motor_and_Prop_Balancer) for rotor blades.
I seem to be interested in a different target. My code might be useful as it allows you to pulse a motor and collect accelerometer measurements with an arduino nano 33 BLE. This chip has an accelerometer on board which simplifies the setup. I also build a client side program to collect the measurements.
